### ISSUE TITLE
Comics don’t Mark as “read” when I view them

### ISSUE THREAD

**Issue by roydbt** [XKCDY/app#102]
When I see a comic for the first time, and then exit it, it doesn’t mark itself as “read” and is still there in the “Unread” tab.

**Comment by codetheweb** [comment]
Just noticed this myself yesterday, thanks for the report.

**Comment by codetheweb** [comment]
Submitted v1.2.10 for review.

**Comment by codetheweb** [comment]
Update is now available. 👍
