### ISSUE TITLE
Crashes after click info and swipe.

### ISSUE THREAD

**Issue by LEXUGE** [XKCDY/app#54]
On iPadOS 14, if I click the info button and then close it via "done". After I swipe to the next comic, app would crash.

**Comment by codetheweb** [comment]
I'm unable to reproduce this, does it happen every single time for you?

**Comment by LEXUGE** [comment]
Yes, specifically on iPad but not iPhone. Both my iPhone and iPad are on iOS 14. Also, for iPad it has more mysterious crashes.

**Comment by codetheweb** [comment]
I took a look through some of the syndicated crash and energy logs. I identified two issues, one that results in a crash and one that results in high CPU usage. I doubt either issue is related to this, but could you test again after I publish a new version?

Alternatively, are you able to run this locally in Xcode? I don't have a physical iPad to test with.

**Comment by LEXUGE** [comment]
Sadly, I am unable to use Xcode because I don’t have MacBooks.

**Comment by codetheweb** [comment]
A new version is now available, can you please update and see if you can still reproduce this?

**Comment by LEXUGE** [comment]
I played around wildly with it, only encountered with one single crash. Not sure if it is still related. At least it’s way better on iPad now.
(It seems like it’s still not that smooth when I am scrolling.)

**Comment by codetheweb** [comment]
Sounds good.

I also noticed that, I created a new issue to track it: https://github.com/XKCDY/app/issues/58.

Thanks for the feedback!
