### ISSUE TITLE
[RESOLVED] App crashes when hitting “Favorites” and no favorites defined

### ISSUE THREAD

**Issue by tingvold** [XKCDY/app#56]
If no favorites has been defined, the app instantly crashes whenever you hit "Favorites". If I define a favorite, it works fine. Removing the favorite again, it crashes. 

Happens on latest iOS 14 beta.

**Comment by codetheweb** [comment]
This should be fixed by a9783ca9c4f58dad37e3d44a56e76fc11aaef9fb.

I'll let you know when an update is released that you can test.

**Comment by codetheweb** [comment]
Version 1.0.3 was just released. If you could test it and confirm that this issue has been resolved I'll go ahead and close it.

**Comment by tingvold** [comment]
Can confirm that it no longer crashes.
