### ISSUE TITLE
Opening a new comic notification should show that comic instead of all comics

### ISSUE THREAD

**Issue by tingvold** [XKCDY/app#60]
If you swipe on a notification for a new comic, the app is opened, and refreshed (showing the new comic in the top left corner). However, you still need to select the comic manually. When swiping from the notification, the app should show the specific comic related to the notification.

Happens on iOS 14 latest beta.

**Comment by codetheweb** [comment]
This isn't a bug per say since there's no logic to do this currently.

But it makes sense to me. 👍
