### ISSUE TITLE
[RESOLVED] Pull down in the list crashes the app

### ISSUE THREAD

**Issue by SiegfriedEhret** [XKCDY/app#67]
Hello!

The list it up to date and there are no new comic.
When I use the "pull down to refresh" thing, the app crashes.

App version: 1.0.3
iOS version: 13.7

Thanks a lot for the app!

**Comment by codetheweb** [comment]
I am aware of this, and I sincerely apologize to you or anyone else who has this issue.
There's a release that will fix this, just waiting for the review process to complete.

I've made a manual test checklist to go through before future releases to hopefully prevent these kinds of issues.

**Comment by SiegfriedEhret** [comment]
Sweet ! Thank you !

**Comment by codetheweb** [comment]
A bugfix release was just fixed, please update and let me know if it works.

**Comment by SiegfriedEhret** [comment]
All good ! Thanks !
