### ISSUE TITLE
Comics not marked as read

### ISSUE THREAD

**Issue by LegoChicken** [XKCDY/app#97]
To reproduce:
1. Open the app on iPhone SE 2020.
2. Tap on a comic to view it.
3. Tap again on the comic to display back button (top left), title & number, alt text at the bottom.
4. Tap on back button.
5. The overview list of comments is shown. The background colour for the comic number just viewed stays as black (not changing to grey).
6. Change to unread view. The comic just viewed is still shown in the unread section. The only comic treated as read is the first new comic after installing the app.

**Comment by codetheweb** [comment]
Can reproduce, thank you for the detailed report.

**Comment by codetheweb** [comment]
v1.2.7 has been submitted for review, I'll let you know when it's published.

**Comment by codetheweb** [comment]
v1.2.7 has now been published and should be available for download / update.

**Comment by LegoChicken** [comment]
Tested the new version and confirmed that it is fixed. Thanks. Any chance of a promo code for XKCDY 😀

**Comment by codetheweb** [comment]
👍 WLY6TLENJR4F
